'use client'

import Link from 'next/link'
import { useState } from 'react'

interface ReportDef {
  key: string
  href: string
  title: string
  description: string
}

const CATEGORIES: Array<{ name: string; reports: ReportDef[] }> = [
  {
    name: 'Sales & Receivables',
    reports: [
      { key: 'invoice-details', href: '/reports/invoice-details', title: 'Invoice Details', description: 'Line-item breakdown for all invoices, grouped by client.' },
      { key: 'revenue-by-client', href: '/reports/revenue-by-client', title: 'Revenue by Client', description: 'Revenue generated by each client over a period.' },
      { key: 'accounts-aging', href: '/reports/accounts-aging', title: 'Accounts Aging', description: 'Outstanding invoice amounts bucketed by age.' },
      { key: 'payments-collected', href: '/reports/payments-collected', title: 'Payments Collected', description: 'Summary of payments received from clients.' },
    ],
  },
  {
    name: 'Expenses & Bills',
    reports: [
      { key: 'expense-report', href: '/reports/expense-report', title: 'Expense Report', description: 'Summary of business expenses grouped by category.' },
      { key: 'item-sales', href: '/reports/item-sales', title: 'Item Sales', description: 'Items and services sold, grouped by name.' },
      { key: 'credit-balance', href: '/reports/credit-balance', title: 'Credit Balance', description: 'Client credit balances from overpayments.' },
    ],
  },
  {
    name: 'Financial Statements',
    reports: [
      { key: 'balance-sheet', href: '/reports/balance-sheet', title: 'Balance Sheet', description: 'Assets, liabilities, and equity at a point in time.' },
      { key: 'profit-and-loss', href: '/reports/profit-and-loss', title: 'Profit and Loss', description: 'Revenue, expenses, and net profit over a period.' },
      { key: 'general-ledger', href: '/reports/general-ledger', title: 'General Ledger', description: 'All transactions organized by account.' },
      { key: 'trial-balance', href: '/reports/trial-balance', title: 'Trial Balance', description: 'Debit and credit balances for all accounts.' },
      { key: 'cash-flow', href: '/reports/cash-flow', title: 'Cash Flow', description: 'Statement of cash flows (indirect method): operating, investing, and financing activities.' },
      { key: 'changes-in-equity', href: '/reports/changes-in-equity', title: 'Statement of Changes in Equity', description: 'Equity account movements with opening and closing balances.' },
      { key: 'account-list', href: '/reports/account-list', title: 'Account List', description: 'Print of the Chart of Accounts with current balances.' },
    ],
  },
  {
    name: 'Sales Tax',
    reports: [
      { key: 'sales-tax-summary', href: '/reports/sales-tax-summary', title: 'Sales Tax Summary', description: 'Taxable sales and tax liability totals.' },
      { key: 'sales-tax-detail', href: '/reports/sales-tax-detail', title: 'GST/HST Detail Report', description: 'Line-by-line GST/HST activity for a filing period.' },
    ],
  },
  {
    name: 'Additional Reports',
    reports: [
      { key: 'bank-reconciliation-summary', href: '/reports/bank-reconciliation-summary', title: 'Bank Reconciliation Summary', description: 'Reconciliation status of bank transactions.' },
      { key: 'journal-entry', href: '/reports/journal-entry', title: 'Journal Entry', description: 'Report of manual journal entries.' },
      { key: 'time-entry-details', href: '/reports/time-entry-details', title: 'Time Entry Details', description: 'Time entries by team member and project.' },
      { key: 'source-documents', href: '/reports/source-documents', title: 'Source Document Coverage', description: 'Transactions missing a receipt, orphaned files, and duplicates.' },
    ],
  },
]

export default function ReportsLandingClient({
  initialFavorites,
}: {
  initialFavorites: string[]
}) {
  const [favorites, setFavorites] = useState<string[]>(initialFavorites)

  async function toggleFavorite(key: string) {
    const res = await fetch('/api/favorite-reports', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ reportKey: key }),
    })
    const data = await res.json()
    setFavorites((prev) =>
      data.favorited ? [...prev, key] : prev.filter((k) => k !== key)
    )
  }

  const allReports = CATEGORIES.flatMap((c) => c.reports)
  const favoriteReports = favorites
    .map((k) => allReports.find((r) => r.key === k))
    .filter((r): r is ReportDef => Boolean(r))

  function ReportCard({ r }: { r: ReportDef }) {
    const isFav = favorites.includes(r.key)
    return (
      <div className="bg-white rounded-lg border border-[#E1E6EB] p-4 hover:shadow-sm transition-shadow relative">
        <button
          onClick={() => toggleFavorite(r.key)}
          className={`absolute top-3 right-3 ${isFav ? 'text-[#FFAB00]' : 'text-[#E1E6EB] hover:text-[#FFAB00]'}`}
          title={isFav ? 'Remove from favorites' : 'Add to favorites'}
        >
          <svg className="w-5 h-5" fill={isFav ? 'currentColor' : 'none'} stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z" />
          </svg>
        </button>
        <Link href={r.href}>
          <h3 className="text-base font-semibold text-[#001B40] mb-1 pr-6">{r.title}</h3>
          <p className="text-sm text-[#576981]">{r.description}</p>
        </Link>
      </div>
    )
  }

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-[40px] font-medium text-[#001B40]" style={{ fontFamily: 'var(--font-heading)' }}>
          Reports
        </h1>
      </div>

      {favoriteReports.length > 0 && (
        <section className="mb-8">
          <h2 className="text-xl text-[#0075DD] mb-4">Favorite Reports</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {favoriteReports.map((r) => <ReportCard key={r.key} r={r} />)}
          </div>
        </section>
      )}

      {CATEGORIES.map((cat) => (
        <section key={cat.name} className="mb-8">
          <h2 className="text-xl text-[#0075DD] mb-4">{cat.name}</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {cat.reports.map((r) => <ReportCard key={r.key} r={r} />)}
          </div>
        </section>
      ))}
    </div>
  )
}
